#!/bin/bash
# Hybrid data collection: distrobox for simulation, pixi for Python components

echo "=== Hybrid Data Collection Setup ==="
echo "This script assumes:"
echo "1. Distrobox container is running with ROS2 simulation built"
echo "2. Pixi environment is available for Python components"
echo "3. Zenoh is used for cross-container communication"
echo ""

echo "=== Step 1: Launch simulation in distrobox ==="
echo "In your distrobox container, run:"
echo "cd /home/damien/ws_aic"
echo "source /opt/ros/kilted/setup.bash"
echo "source install/setup.bash"
echo "ros2 launch aic_bringup aic_gz_bringup.launch.py \"
echo "  spawn_task_board:=true \"
echo "  spawn_cable:=true \"
echo "  cable_type:=sfp_sc_cable \"
echo "  attach_cable_to_gripper:=true \"
echo "  ground_truth:=true \"
echo "  gazebo_gui:=false"
echo ""

echo "=== Step 2: Wait for simulation to initialize ==="
echo "Wait about 10-15 seconds for Gazebo to fully load..."
echo ""

echo "=== Step 3: In host system, activate pixi and launch components ==="
echo "Open new terminal in host system and run:"
echo ""
echo "# Terminal 1: Zenoh router"
echo "cd /home/damien/ws_aic/src/aic"
echo "pixi shell"
echo "export RMW_IMPLEMENTATION=rmw_zenoh_cpp"
echo "export ROS_DOMAIN_ID=0"
echo "ros2 run rmw_zenoh_cpp rmw_zenohd"
echo ""
echo "# Terminal 2: AutoDataCollector policy"
echo "cd /home/damien/ws_aic/src/aic"
echo "pixi shell"
echo "export RMW_IMPLEMENTATION=rmw_zenoh_cpp"
echo "export ROS_DOMAIN_ID=0"
echo "ros2 run aic_model aic_model --ros-args \"
echo "  -p use_sim_time:=true \"
echo "  -p policy:=my_policy_node.AutoDataCollector"
echo ""
echo "# Terminal 3: AIC Engine"
echo "cd /home/damien/ws_aic/src/aic"
echo "pixi shell"
echo "export RMW_IMPLEMENTATION=rmw_zenoh_cpp"
echo "export ROS_DOMAIN_ID=0"
echo "ros2 run aic_engine aic_engine --ros-args \"
echo "  -p config_file_path:=\$(ros2 pkg prefix aic_engine)/share/aic_engine/config/sample_config.yaml \"
echo "  -p model_node_name:=aic_model \"
echo "  -p ground_truth:=true \"
echo "  -p use_sim_time:=true"
echo ""

echo "=== Notes ==="
echo "1. Make sure ROS_DOMAIN_ID matches between distrobox and host"
echo "2. Zenoh should handle cross-container communication"
echo "3. Data will be saved to datasets/cable_insertion/ in your pixi environment"
echo "4. If connection issues occur, try setting: export FASTDDS_DEFAULT_PROFILES=fastdds.xml"
